// src/Todo/todo.solid.tsx
/** @jsxImportSource solid-js */

import { For } from "solid-js";
import { type SetStoreFunction, createStore } from "solid-js/store";

import type { Todo, TodoList } from "./types";

let AddPanel = (props: {
  todoList: TodoList;
  setTodoList: SetStoreFunction<TodoList>;
}) => {
  let inputEl!: HTMLInputElement;
  let onClick = () => {
    let contents = inputEl.value;
    props.setTodoList("todos", props.todoList.todos.length, {
      contents,
      completed: false
    });
    inputEl.value = "";
  };
  return (
    <div>
      <button onClick={onClick}>Add</button>
      <input type="text" ref={inputEl} />
    </div>
  );
};

let ItemCount = (props: { todoList: TodoList }) => {
  // This must be behind a thunk so the component reacts correctly
  let count = () => props.todoList.todos.filter(item => item.completed).length;
  return (
    <div>
      Completed: <span>{count()}</span>
    </div>
  );
};

let TodoItem = (props: {
  item: Todo;
  setTodo: (item: Partial<Todo>) => void;
}) => {
  let onClick = () => {
    props.setTodo({ completed: !props.item.completed });
  };
  return (
    <li>
      {props.item.contents}
      <button onClick={onClick}>
        {!props.item.completed ? "Done" : "Undone"}
      </button>
    </li>
  );
};

export let SolidTodo = () => {
  let [todoList, setTodoList] = createStore<TodoList>({ todos: [] });
  return (
    <div>
      <AddPanel todoList={todoList} setTodoList={setTodoList} />
      <ItemCount todoList={todoList} />
      <ul>
        <For each={todoList.todos}>
          {(item, i) => (
            <TodoItem
              item={item}
              setTodo={item => setTodoList("todos", i(), item)}
            />
          )}
        </For>
      </ul>
    </div>
  );
};

export default SolidTodo;

// src/Todo/todo.react.tsx
import { observer, useLocalObservable } from "mobx-react";
import { useRef } from "react";
import type { Todo, TodoList } from "./types";

let AddPanel = (props: { todoList: TodoList }) => {
  let ref = useRef<HTMLInputElement>(null);
  let onClick = () => {
    let contents = ref.current!.value;
    props.todoList.todos.push({
      contents,
      completed: false
    });
    ref.current!.value = "";
  };
  return (
    <div>
      <button onClick={onClick}>Add</button>
      <input type="text" ref={ref} />
    </div>
  );
};

let ItemCount = observer((props: { todoList: TodoList }) => {
  let count = props.todoList.todos.filter(item => item.completed).length;
  return (
    <div>
      Completed: <span>{count}</span>
    </div>
  );
});

let TodoItem = observer((props: { item: Todo }) => {
  let onClick = () => {
    props.item.completed = !props.item.completed;
  };
  return (
    <li>
      {props.item.contents}
      <button onClick={onClick}>
        {!props.item.completed ? "Done" : "Undone"}
      </button>
    </li>
  );
});

export let ReactTodo = observer(() => {
  let todoList = useLocalObservable<TodoList>(() => ({ todos: [] }));
  return (
    <div>
      <AddPanel todoList={todoList} />
      <ItemCount todoList={todoList} />
      <ul>
        {todoList.todos.map((item, i) => (
          <TodoItem key={i} item={item} />
        ))}
      </ul>
    </div>
  );
});
